import path from 'node:path';
import { DESKTOP_PLATFORMS, MOBILE_PLATFORMS } from './constants.js';
import { appIdFromName, dedupe, hasAny, writeBinaryFileSafe, writeFileSafe, writeJson } from './utils.js';

const TAURI_DEFAULT_ICON_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAIeElEQVR4nK1XCXBVZxX+t3vv2192sBCWLGWHBIWyVS2L1Bad2CLFaWtxGJTSOlNnEKqOgDiZKbVqZ9RabUew2DrWwWlnIMgyI2iFFGjipCRGlgYiSUjykrcv997//r/nvy9QkCWh7Ztk3su9ef855zvf951z8fJnVqCP88Lwg7F6Q0iqX4nEnXyffdSgBCMqJHJsgaUj3dgIriGNSEQxYpCFGEkyd5yAOtwSiGcswj1MohKvUxLWRSnBkqRsEu3P0u6YSbhBJfIyySA5/okloKqOQ+AynxN85O7EukVjsivLA3yyl4mQaoPp4ExvmnWc7PU07O3w//psVLsY0sWV9sibojlSDkAAkrKIeGBietVTs2K/DPl5KVJnq+Px0NkS58NAG4RF+R/ag9t2tYXqGdynBK7epCW0at7dI6pcBV8/M75lw5zBXxkY+a/U053Qzp4ZME5eimvtNifZAl2MQgTSkgjXjM0uqQ7ymUcu+d5U6ZF8unfWAtVzBfvXJiXXPzoz9iM7R01NF0bLZc/fXmsL/bBtUD+esbFQ+ai+TwjzyauqU5uXTkyt4VliL5iQfmiTjXduf7f4GwFNKBScESMAlZMsx05lAa+oXxQ5qKCmumR/bgvv2NZY/HhXmv6XESQNiphOXRHIvgyNHLroezuWo+cXlWdXOjbhVWXm7J6k1to6YLQqYkKyYkQJqL5bDpbfmxv9/SifrDzR7dvbcM7/0u9Oh+rhIOSBwBAVgyqUHAUkQ3XotU8T2onL3mboQnzOmNwDyMFoQpBP33/R/9JQcDwiEipcvToOzi7O3Pt+t2joN3XkMA8Kag7Jew6SGY7RKJ9TCAh4upK0R6d5wimOWJDUK0t7myoKrVoVcvPR0vuO93iOBDTpeoiL8m3JRwi10pnk4a5gw6XKJU/kFn31xZAhdPAdgfKyQ09MTW7cff/lzteWX77w/Xuir6o+wOGCEklzkNyhTt8uBEkpZcwqNe/jwrXNqwiQW4IPv8RKO6mq+Q9Hv/Lshb7F63flAmVVyMxamFA9C8SrLTPnr62J/cTDRACMSPvCpMTausrU02mbuEEYBD0T1U8hJx9mTIBXU3y9J9xKBZjwnIjMeeS5gZkPbiZWBmp2EM2lejG8I8UNqKSqwK5VZ1mcZhVfNJsYkwrtuVJeJTHKcJIEv4C+IOyh0o/x9X50AwISEwYBxUBt3bZIzZc301zSFsxA/q7Wk6Hzx18VmgHJSNdqW/qNo8qMdEN4NSYMNQFO9XkOEPwhh0K6U4RI3g0hmYSQ17eA/V/dlFoZnimf+blIzZe2skyMO7pPK27Z++OSpre2uNNOM4BgknsZov8e1Frrj5esXDM1Xg8Jefed9r/81wu+1/2aKhlJUAaaWmwtdDkAr84Ea5PydkYkoTbK0MCsFTuwAG0ZPlbUevCnpSf+tMXxhkieG3lnV0Tz6Vg7cNG75+9dnj1KggmTOBBcQY8huB02BF4+PrNWyVAV3dTvOaym5bUcINdWD32X2bKqedmSinsU0Y1Y9/ni5rc3Op7AUFzhQHtc+QAXJLaydkBHmjqeQ75BXVDlnOp2zKRo3fTE86NDdoUCvH1Abzwd0U+Cf2BxjRteRUCq8gRH2dGTlikU1Ct0vvEVIB7i3pAGAcETOYrO+OJ34lULNhBupYreb/hB4GJTA9I8FEu1FoAv2NhRGv12TWzLQ5MTGx0bc6pJtrM1/KwtlF2j6+yYXbNkSIkpssKjp7l/Ozby9H/wzlAymNg5mahauLp3/mM/IyaoAq73fPab+8btq5+kR7vOgBkz20F8dpk5b92M+AtTysyF3MI28wrtjy0F2//Z7TkKe8MN+8E1KnAxQIJ5wu4Nh3Mg5ACoIp8gtCQzZuoKzE0ErTJBHVmliOyo6sXEsdSKxGBuoLqq9DNT7souRPCZeYS2pzX8wsstoa1BIObNlhNy3aIF2GBhZ9x0CGWC6QHXcN3pCvBFLzULzaukqoE0veq6HutpkYS5BFYmE9CcAnVqf07reu5YyeoXmwq+62MSD7sRufVDlVoycs7VMNORWTi21tvTfso9HQKH24/+3Cwa9+lkec1q4thmUcu+7b7L/zkmNA8B/VgBA+vdGaOj8ZjxrYPntd9GHC/4gFC+L9CwG5FSATA8NX72/d2Ln9qvKvf2nTtWvv/5hRCAKgkgxXxwQjs8egLmVgaS7VNtcHMH6TEwMOX/WSOM6F0VS4ORc43CtlJX1XuzfePDcQz6pBRpqcEOSOIxMKBCO1harmXjl3xdre8J3a+r/RsRimk2ESXcTIMpUYkxIA/wc0tGpy59Mj1j2abUglW7BXw/ePad3ZIZND84h01A2TBl1EzBBiDiyYlz62AU8vTYGXV6KtLs7T3bBihJlYCkGpNEfRAOhZmh5Bn5zMP1/TA7zIIx0wSc86mjv3kQvh9V/38r+G9IQFUimU68/R/8C2CekS2rnA7y48mKuY86voJiPdXfBr4Qg2sCOOC6Zq60ck7fgq/vjFffu4ZlE6bUPGzUu29sCHQ2HQIUmPKH2y67NywkCmfotcq85/NPHkiOq10GkgMSejDI0jJiXc0sHe0ElWjQomqz4K5pgAxSKIB1o5Lmt7aXvPeXrUL3UjRM8FtvRLAKQBLuCIvU1u2ITVmySalCEdD1hasjQbr+oJDQ0oNRCPx06Ow/3oDK1cCSt4N+uJ1QqnVI2U+gs/lwoLv1TeX9wPhCQMYPrWLYgf3AyiQBkdOF7Ud+Udb4+uMg2ZPC8KvKR/x8ONyDCchLDSmTQ88B4gDh/sLxju4vUoOJ5ZK9LD3YA/eR2hkEkBMQ4Z/kw6lUBypicmbA1uVwLd7boUnRMbQ0gmMyzI2AO4zuNPjInw0BUqUQ13CYhvMkkEPmAfc+QuArr/8BFmhIo44ScwcAAAAASUVORK5CYII=';

function createRootPackageJson(projectName, platforms, hasMobile, hasDesktop) {
  const dependencies = {
    svelte: '^4.2.19',
  };

  const devDependencies = {
    '@sveltejs/vite-plugin-svelte': '^3.1.2',
    vite: '^5.4.19',
  };

  if (hasMobile) {
    dependencies['@capacitor/core'] = '^6.1.0';
    devDependencies['@capacitor/cli'] = '^6.1.0';
  }

  if (hasDesktop) {
    devDependencies['@tauri-apps/cli'] = '^2.0.0';
  }

  const scripts = {
    dev: 'vite',
    build: 'vite build',
    preview: 'vite preview',
  };

  if (hasMobile) {
    scripts['cap:sync'] = 'pnpm build && cap sync';

    if (platforms.includes('ios')) {
      scripts['cap:add:ios'] = 'cap add ios';
      scripts['cap:open:ios'] = 'cap open ios';
    }

    if (platforms.includes('android')) {
      scripts['cap:add:android'] = 'cap add android';
      scripts['cap:open:android'] = 'cap open android';
    }
  }

  if (hasDesktop) {
    scripts['desktop:dev'] = 'tauri dev';
    scripts['desktop:build'] = 'tauri build';
  }

  return {
    name: projectName,
    private: true,
    version: '0.1.0',
    packageManager: 'pnpm@10.25.0',
    type: 'module',
    scripts,
    dependencies,
    devDependencies,
  };
}

function createRootReadme(projectName, platforms, hasMobile, hasDesktop) {
  const lines = [
    `# ${projectName}`,
    '',
    'Scaffold generated by SNative CLI.',
    '',
    '## Prerequisites',
    '',
    '- Node.js 18+',
    '- pnpm 10+',
    '- Native toolchains only if you will run mobile/desktop targets',
    '',
    '## Quick Start',
    '',
    '```bash',
    'pnpm install',
    'pnpm dev',
    '```',
    '',
    '## Build and Preview',
    '',
    '```bash',
    'pnpm build',
    'pnpm preview',
    '```',
    '',
    '## Project structure',
    '',
    '```txt',
    'app/',
    '  index.html',
    '  main/',
    '    App.svelte',
    '    app.css',
    '    main.js',
    '  config/',
    '  assets/',
    '  models/',
    '  routes/',
    '  services/',
    '  stores/',
    '  test/',
    '  themes/',
    '  ui/',
    '  modules/',
    '    home/Home.svelte',
    'native/',
    '  mobile/   # optional',
    '  desktop/  # optional',
    'dist/       # generated after pnpm build',
    '```',
  ];

  if (hasMobile) {
    lines.push('', '## Mobile Runtime (Capacitor)', '', '```bash', 'pnpm cap:sync', '```');

    if (platforms.includes('ios')) {
      lines.push('', '```bash', 'pnpm cap:add:ios', '```');
    }

    if (platforms.includes('android')) {
      lines.push('', '```bash', 'pnpm cap:add:android', '```');
    }
  }

  if (hasDesktop) {
    lines.push('', '## Desktop Runtime (Tauri)', '', '```bash', 'pnpm desktop:dev', '```');
  }

  lines.push(
    '',
    '## Documentation',
    '',
    '- `GUIDE.es.md`: operating guide (Spanish)',
    '- `GUIDE.en.md`: operating guide (English)',
    '',
    `Selected platforms: ${platforms.join(', ')}`,
  );

  return `${lines.join('\n')}\n`;
}

function createGuideEs() {
  return `# GUIDE (ES)

Guía operativa para equipos de producto que usan el template SNative.

## 1. Objetivo del proyecto

Este scaffold separa claramente:

- producto web en \`app/\`
- adaptadores nativos opcionales en \`native/\`

La intención es mantener la lógica de negocio y UI en un solo lugar y conectar runtimes nativos solo cuando el producto lo requiera.

## 2. Requisitos de entorno

- Node.js 18 o superior
- pnpm 10 o superior
- Para mobile (Capacitor): Xcode/Android Studio según plataforma
- Para desktop (Tauri): toolchain de Rust y dependencias del sistema operativo

## 3. Flujo diario recomendado

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

Para validar entrega:

\`\`\`bash
pnpm build
pnpm preview
\`\`\`

## 4. Estructura de trabajo

\`\`\`txt
app/
  main/         # bootstrap web (App.svelte, estilos base, entrypoint)
  modules/      # features y pantallas de negocio
  routes/       # configuración y navegación de rutas
  services/     # integración con APIs y side effects
  stores/       # estado compartido de la aplicación
  ui/           # componentes reutilizables
  assets/       # recursos estáticos
native/
  mobile/       # integración Capacitor (opcional)
  desktop/      # integración Tauri (opcional)
\`\`\`

## 5. Flujo mobile (si fue habilitado)

\`\`\`bash
pnpm cap:sync
\`\`\`

Primer setup por plataforma:

\`\`\`bash
pnpm cap:add:ios
pnpm cap:add:android
\`\`\`

Apertura de IDE nativo:

\`\`\`bash
pnpm cap:open:ios
pnpm cap:open:android
\`\`\`

## 6. Flujo desktop (si fue habilitado)

\`\`\`bash
pnpm desktop:dev
pnpm desktop:build
\`\`\`

## 7. Convenciones de equipo

- Mantén \`app/modules\` como unidad principal de features.
- Evita mezclar lógica de producto dentro de \`native/\`.
- Mantén nombres de carpetas y archivos consistentes con el dominio funcional.
- Usa \`snative.config.json\` como referencia de plataformas habilitadas.

## 8. Checklist de release interno

- \`pnpm build\` sin errores
- navegación principal validada
- assets y variables de entorno revisadas
- runtimes nativos sincronizados solo si aplican
`; 
}

function createGuideEn() {
  return `# GUIDE (EN)

Operating guide for product teams using the SNative template.

## 1. Project intent

This scaffold enforces a clear separation between:

- web product code in \`app/\`
- optional native adapters in \`native/\`

The goal is to keep business logic and UI centralized while enabling native runtimes only when needed.

## 2. Environment requirements

- Node.js 18+
- pnpm 10+
- For mobile (Capacitor): Xcode/Android Studio depending on target
- For desktop (Tauri): Rust toolchain and OS system dependencies

## 3. Recommended daily workflow

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

For delivery validation:

\`\`\`bash
pnpm build
pnpm preview
\`\`\`

## 4. Working structure

\`\`\`txt
app/
  main/         # web bootstrap (App.svelte, global styles, entrypoint)
  modules/      # product features and screens
  routes/       # route config and navigation
  services/     # API integrations and side effects
  stores/       # shared application state
  ui/           # reusable components
  assets/       # static resources
native/
  mobile/       # Capacitor integration (optional)
  desktop/      # Tauri integration (optional)
\`\`\`

## 5. Mobile workflow (if enabled)

\`\`\`bash
pnpm cap:sync
\`\`\`

Initial platform setup:

\`\`\`bash
pnpm cap:add:ios
pnpm cap:add:android
\`\`\`

Open native IDE workspace:

\`\`\`bash
pnpm cap:open:ios
pnpm cap:open:android
\`\`\`

## 6. Desktop workflow (if enabled)

\`\`\`bash
pnpm desktop:dev
pnpm desktop:build
\`\`\`

## 7. Team conventions

- Keep \`app/modules\` as the primary feature boundary.
- Do not move product logic into \`native/\`.
- Use domain-consistent folder and file naming.
- Treat \`snative.config.json\` as the source of truth for enabled platforms.

## 8. Internal release checklist

- \`pnpm build\` passes
- core navigation is validated
- assets and env variables are reviewed
- native runtimes are synced only when applicable
`; 
}

function createEnvExample() {
  return '# Add runtime environment variables here\n';
}

function createRouterConfig() {
  return `import Home from '../modules/home/Home.svelte';
import NotFound from '../modules/errors/NotFound.svelte';

export const routes = {
  home: Home,
  'not-found': NotFound,
};

export const defaultRoute = 'home';
export const notFoundRoute = 'not-found';
`;
}

function createRouterGoto() {
  return `import { get, writable } from 'svelte/store';
import { routes, defaultRoute, notFoundRoute } from './config.js';

function normalizePath(pathname = '/') {
  const url = new URL(pathname || '/', 'http://localhost');
  const cleaned = url.pathname
    .replace(/\\/{2,}/g, '/')
    .replace(/\\/+$/g, '');

  return cleaned || '/';
}

function pathToRoute(pathname) {
  const normalized = normalizePath(pathname);

  if (normalized === '/') {
    return defaultRoute;
  }

  const segment = normalized.replace(/^\\//, '');
  return routes[segment] ? segment : notFoundRoute;
}

function routeToPath(name) {
  if (!name || name === defaultRoute) {
    return '/';
  }

  return '/' + name;
}

const initialRoute =
  typeof window !== 'undefined'
    ? pathToRoute(window.location.pathname)
    : defaultRoute;

export const currentRoute = writable(initialRoute);

if (typeof window !== 'undefined' && window.history) {
  const initialPath = routeToPath(initialRoute);
  if (normalizePath(window.location.pathname) !== initialPath) {
    window.history.replaceState({ route: initialRoute }, '', initialPath);
  }

  window.addEventListener('popstate', () => {
    currentRoute.set(pathToRoute(window.location.pathname));
  });
}

export function goto(name, options = {}) {
  if (!routes[name]) {
    return false;
  }

  const replace = Boolean(options.replace);
  const nextPath = routeToPath(name);
  currentRoute.set(name);

  if (typeof window !== 'undefined' && window.history) {
    const currentPath = normalizePath(window.location.pathname);

    if (currentPath !== nextPath) {
      const state = { route: name };
      if (replace) {
        window.history.replaceState(state, '', nextPath);
      } else {
        window.history.pushState(state, '', nextPath);
      }
    }
  }

  return true;
}

export function goBack() {
  if (typeof window !== 'undefined' && window.history) {
    window.history.back();
  }
}

export function getCurrentRoute() {
  return get(currentRoute);
}
`;
}

function createRouterIndex() {
  return `export { currentRoute, getCurrentRoute, goto, goBack } from './goto.js';
export { routes, defaultRoute, notFoundRoute } from './config.js';
export { default as Router } from './Router.svelte';
`;
}

function createRouterSvelte() {
  return `<script>
  import { currentRoute } from './goto.js';
  import { defaultRoute, routes } from './config.js';

  $: ActiveComponent = routes[$currentRoute] || routes[defaultRoute];
</script>

<div class="route-wrap">
  <svelte:component this={ActiveComponent} />
</div>

<style>
  .route-wrap {
    min-height: 100%;
    height: 100%;
  }
</style>
`;
}

function createAppSvelte() {
  return `<script>
  import Router from '../routes/Router.svelte';
</script>

<Router />
`;
}

function createHomeSvelte() {
  return `<main class="home">
  <h1>Hola mundo</h1>
</main>

<style>
  .home {
    min-height: 100vh;
    display: grid;
    place-items: center;
  }

  h1 {
    margin: 0;
    font-size: 2rem;
    font-weight: 600;
  }
</style>
`;
}

function createNotFoundSvelte() {
  return `<main class="not-found">
  <h1>No encontrado</h1>
</main>

<style>
  .not-found {
    min-height: 100vh;
    display: grid;
    place-items: center;
  }

  h1 {
    margin: 0;
    font-size: 2rem;
    font-weight: 600;
  }
</style>
`;
}

function createCapacitorFiles(projectName, platforms) {
  const appId = appIdFromName(projectName);
  const config = {
    appId,
    appName: projectName,
    webDir: 'dist',
  };

  if (platforms.includes('ios')) {
    config.ios = { path: 'native/mobile/ios' };
  }

  if (platforms.includes('android')) {
    config.android = { path: 'native/mobile/android' };
  }

  return [
    {
      filePath: 'capacitor.config.json',
      content: `${JSON.stringify(config, null, 2)}\n`,
    },
    {
      filePath: 'native/mobile/README.md',
      content: `# Mobile (Capacitor)\n\nEnabled platforms: ${platforms.filter((item) => MOBILE_PLATFORMS.includes(item)).join(', ')}\n\nCommands:\n\n\`\`\`bash\npnpm cap:sync\n\`\`\`\n`,
    },
  ];
}

function normalizeRustPackageName(projectName) {
  const base = (projectName || 'snative-app').replace(/[^a-z0-9_-]/gi, '-').toLowerCase();
  const cleaned = base.replace(/-+/g, '-').replace(/^[-_]+|[-_]+$/g, '');

  if (!cleaned) {
    return 'snative-app';
  }

  return /^[a-z]/.test(cleaned) ? cleaned : `app-${cleaned}`;
}

function rustLibNameFromPackageName(packageName) {
  const normalized = String(packageName || 'snative_app').replace(/-/g, '_');
  return /^[a-z_]/.test(normalized) ? normalized : `app_${normalized}`;
}

function createTauriCargoToml(projectName) {
  const rustPackageName = normalizeRustPackageName(projectName);
  const rustLibName = rustLibNameFromPackageName(rustPackageName);

  return `[package]
name = "${rustPackageName}"
version = "0.1.0"
description = "SNative desktop shell"
authors = ["SNative"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "${rustLibName}"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`;
}

function createTauriMainRs(projectName) {
  const rustPackageName = normalizeRustPackageName(projectName);
  const rustLibName = rustLibNameFromPackageName(rustPackageName);

  return `#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
  ${rustLibName}::run();
}
`;
}

function createTauriLibRs() {
  return `#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
  tauri::Builder::default()
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
`;
}

function createTauriFiles(projectName, platforms) {
  const appId = appIdFromName(projectName);

  return [
    {
      filePath: 'native/desktop/src-tauri/tauri.conf.json',
      content: `${JSON.stringify({
        $schema: 'https://schema.tauri.app/config/2',
        productName: projectName,
        identifier: appId,
        build: {
          frontendDist: '../../../dist',
          beforeBuildCommand: 'pnpm build',
          devUrl: 'http://localhost:5173',
          beforeDevCommand: 'pnpm dev',
        },
        app: {
          windows: [{ title: projectName, width: 1200, height: 760 }],
          security: { csp: null },
        },
      }, null, 2)}\n`,
    },
    {
      filePath: 'native/desktop/src-tauri/Cargo.toml',
      content: createTauriCargoToml(projectName),
    },
    {
      filePath: 'native/desktop/src-tauri/build.rs',
      content: 'fn main() {\n  tauri_build::build()\n}\n',
    },
    {
      filePath: 'native/desktop/src-tauri/src/main.rs',
      content: createTauriMainRs(projectName),
    },
    {
      filePath: 'native/desktop/src-tauri/src/lib.rs',
      content: createTauriLibRs(),
    },
    {
      filePath: 'native/desktop/src-tauri/capabilities/default.json',
      content: `${JSON.stringify({
        $schema: '../gen/schemas/desktop-schema.json',
        identifier: 'default',
        description: 'enables the default permissions',
        windows: ['main'],
        permissions: ['core:default'],
      }, null, 2)}\n`,
    },
    {
      filePath: 'native/desktop/src-tauri/.gitignore',
      content: '/target\n',
    },
    {
      filePath: 'native/desktop/README.md',
      content: `# Desktop (Tauri)\n\nEnabled platforms: ${platforms.filter((item) => DESKTOP_PLATFORMS.includes(item)).join(', ')}\n\nCommands:\n\n\`\`\`bash\npnpm desktop:dev\n\`\`\`\n`,
    },
  ];
}

export async function generateProject({ targetDir, config }) {
  const platforms = dedupe(config.platforms.includes('web') ? config.platforms : ['web', ...config.platforms]);
  const hasMobile = hasAny(platforms, MOBILE_PLATFORMS);
  const hasDesktop = hasAny(platforms, DESKTOP_PLATFORMS);

  await writeJson(path.join(targetDir, 'package.json'), createRootPackageJson(config.projectName, platforms, hasMobile, hasDesktop));
  await writeFileSafe(path.join(targetDir, '.gitignore'), 'node_modules\n.DS_Store\ndist\n.env\n');
  await writeJson(path.join(targetDir, 'snative.config.json'), {
    schemaVersion: 2,
    projectName: config.projectName,
    platforms,
    runtimes: {
      mobile: hasMobile ? 'capacitor' : null,
      desktop: hasDesktop ? 'tauri' : null,
    },
  });

  await writeFileSafe(path.join(targetDir, 'README.md'), createRootReadme(config.projectName, platforms, hasMobile, hasDesktop));
  await writeFileSafe(path.join(targetDir, '.env.example'), createEnvExample());
  await writeFileSafe(path.join(targetDir, 'GUIDE.es.md'), createGuideEs());
  await writeFileSafe(path.join(targetDir, 'GUIDE.en.md'), createGuideEn());

  await writeFileSafe(path.join(targetDir, 'app/index.html'), `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${config.projectName}</title>\n  </head>\n  <body>\n    <div id="app"></div>\n    <script type="module" src="/main/main.js"></script>\n  </body>\n</html>\n`);

  await writeFileSafe(path.join(targetDir, 'vite.config.js'), `import { defineConfig } from 'vite';\nimport { svelte } from '@sveltejs/vite-plugin-svelte';\n\nexport default defineConfig({\n  root: 'app',\n  build: {\n    outDir: '../dist',\n    emptyOutDir: true,\n  },\n  plugins: [svelte()],\n});\n`);

  await writeFileSafe(path.join(targetDir, 'svelte.config.js'), 'export default {};\n');

  await writeFileSafe(path.join(targetDir, 'app/main/main.js'), `import './app.css';\nimport App from './App.svelte';\n\nnew App({\n  target: document.getElementById('app'),\n});\n`);

  await writeFileSafe(path.join(targetDir, 'app/main/app.css'), `html, body, #app {\n  margin: 0;\n  min-height: 100%;\n}\n\nbody {\n  font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Arial, sans-serif;\n}\n`);

  await writeFileSafe(path.join(targetDir, 'app/main/App.svelte'), createAppSvelte());

  await writeFileSafe(path.join(targetDir, 'app/routes/config.js'), createRouterConfig());
  await writeFileSafe(path.join(targetDir, 'app/routes/goto.js'), createRouterGoto());
  await writeFileSafe(path.join(targetDir, 'app/routes/index.js'), createRouterIndex());
  await writeFileSafe(path.join(targetDir, 'app/routes/Router.svelte'), createRouterSvelte());

  await writeFileSafe(path.join(targetDir, 'app/modules/home/Home.svelte'), createHomeSvelte());
  await writeFileSafe(path.join(targetDir, 'app/modules/errors/NotFound.svelte'), createNotFoundSvelte());

  await writeFileSafe(path.join(targetDir, 'app/config/.gitkeep'), '');
  await writeFileSafe(path.join(targetDir, 'app/assets/.gitkeep'), '');
  await writeFileSafe(path.join(targetDir, 'app/models/.gitkeep'), '');
  await writeFileSafe(path.join(targetDir, 'app/services/.gitkeep'), '');
  await writeFileSafe(path.join(targetDir, 'app/stores/.gitkeep'), '');
  await writeFileSafe(path.join(targetDir, 'app/test/.gitkeep'), '');
  await writeFileSafe(path.join(targetDir, 'app/themes/.gitkeep'), '');
  await writeFileSafe(path.join(targetDir, 'app/ui/.gitkeep'), '');

  if (hasMobile) {
    const files = createCapacitorFiles(config.projectName, platforms);
    for (const file of files) {
      await writeFileSafe(path.join(targetDir, file.filePath), file.content);
    }
  }

  if (hasDesktop) {
    const files = createTauriFiles(config.projectName, platforms);
    for (const file of files) {
      await writeFileSafe(path.join(targetDir, file.filePath), file.content);
    }

    const iconBytes = Buffer.from(TAURI_DEFAULT_ICON_PNG_BASE64, 'base64');
    await writeBinaryFileSafe(path.join(targetDir, 'native/desktop/src-tauri/icons/icon.png'), iconBytes);
  }

  return {
    hasMobile,
    hasDesktop,
    normalizedConfig: {
      ...config,
      platforms,
    },
  };
}
